// The schema defines the structure of the Product documents in MongoDB,

const mongoose = require("mongoose");

const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String },
    price: { type: Number, required: true },
    category: { type: String, required: true },
    // path to image file, stored as string in MongoDB, but used as src in frontend <img src={product.image} />
    image: { type: String },
    popular: { type: Boolean, default: false },
  },

  // ----Config options for the schema:-----
  // { timestamps: true }
  //- when we convert document to JSON> include virtual fields like id (which returns _id as string) in the JSON output, so frontend can use product.id instead of product._id
  { timestamps: true, toJSON: { virtuals: true } }, // createdAt, updatedAt automatic + include id virtual in JSON
);

module.exports = mongoose.model("Product", productSchema);

// _id = primary key, auto-generated by MongoDB (ObjectId, not a string like in json-server)
//  id = virtual field that returns _id as a string (for easier handling in frontend, since json-server used string ids)
