const mongoose = require("mongoose");

const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String },
    price: { type: Number, required: true },
    category: { type: String, required: true },
    image: { type: String },
    popular: { type: Boolean, default: false },
  },
  // { timestamps: true } // For Json-server
  { timestamps: true, toJSON: { virtuals: true } }, // createdAt, updatedAt automatic + include id virtual in JSON
);

module.exports = mongoose.model("Product", productSchema);

// _id = primary key, auto-generated by MongoDB (ObjectId, not a string like in json-server)
//  id = virtual field that returns _id as a string (for easier handling in frontend, since json-server used string ids)

// *** Use toJSON: { virtuals: true } when you want virtual fields like id to appear in API JSON responses.
// Use it if the frontend needs id instead of _id
